apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx-pod
      image: nginx
      ports:
      - containerPort: 80

```kubectl apply -f Pod.yaml
   kubectl get pod 
   kubectl describe pod <nginx>
