apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-demo
  labels:
    app: nginx-app
spec:
  replicas: 3
  selector:
   matchExpressions:
     - key: app
       operator: In
       values:
         - nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx-container-1
          image: nginx:1.14.2
          ports:
            - containerPort: 80



``` 
kubectl apply -f <ReplicaSet.yaml>
```

```
kubectl get rs/replicaset
```

```
kubectl describe rs
```
