apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-demo
  labels:
    env: dev
spec:
  replicas: 4
  selector:
    env: dev
  template:
    metadata:
      name: rc-demo
      labels:
        env: dev
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
